# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_songs_in_favrouite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='in_favrouite',
            new_name='is_favourite',
        ),
    ]
